### ISSUE TITLE
Meinung?

### ISSUE THREAD

**Issue by aselim21** [bkumas/GDW-WS20-21#1]
**Eine Webseite, wo man Sprechen üben kann.**
1. Anmelden-
username,
password,
welche sprachen man spricht + Niveau dazu,
Interessen-
Alter-
Status(Student, Arbeitet...)
Profilfoto(man muss sich selber nicht zeigen)-
Online/Offline-
Liste mit Freunden-
Punkte PX(wie viel man gesprochen hat)
2. Sprachen -
Englisch, Deutsch, Spanisch, Japanisch, Koreanisch, Französisch
3. Gesprächsraum- Wählen->
Aufteilen nach Interesse, Alter, Status, Niveau, Zufällig()

**Comment by aselim21** [comment]
Das ist unsere Idee und grob wie das ganze funktionieren wird. Wir haben in Wiki auch unser Szenario. Finden Sie unsere Idee gut und wie können wir sie verbessern? Wir hatten auch die Idee, dass man Google Translate irgendwie benutzen kann oder Google speech. Das wäre sehr hilfreich wenn z.B. einer sehr schlechte Aussprache hat, oder jemand sehr schnell spricht. Und Google Translate wenn man ein Wort nicht kennt. Wir haben auch die API von Duden.de gefunden, aber das gilt leider nur für Deutsch. Ob andere Sprachen solche Wörterbücher haben, kennen wir nicht.

**Comment by nathaliekhn** [comment]
Hallo Zusammen,

aus den Stichpunkten wird mir leider nicht ganz ersichtlich, wie ihr die Problemstellung, welche im Szenario genannt wird, lösen wollt. Könnt ihr die Stichpunkte vielleicht einmal textlich ausformulieren?

Aktuell verstehe ich euer System so, dass sich ein Nutzer anmelden kann, über ein Profil verfügt, Freundeslisten hat und Chaträumen beitreten kann. Ist das richtig? Wenn ja, wo steckt eure Anwendungslogik? Euer System muss noch etwas leisten können. Aktuell habt ihr quasi nur eine Ein- und Ausgabe. Da muss noch etwas mehr passieren. Gestaltet mal ein Domänenmodell, um einen besseren Überblick über die Problemdomäne zu bekommen. Dann fällt euch vielleicht eine Erweiterung ein.

**Comment by aselim21** [comment]
Hi, 

Danke für die Antwort. 
Wir haben noch ein bisschen unsere Idee erweitert und versucht des ausführlicher in Wiki zu beschreiben. Kannst du gerne dort anschauen? Wir haben auch eine Tabelle erstellt. Wir wollen gerne deine Meinung hören. Passt unsere Idee zu dem Projekt, das wir machen müssen oder sollen wir besser etwas anderes machen. Wir sind auch nicht sicher, ob das was wir wollen machbar ist. 

Wir verbleiben in Erwartung deiner Antwort.

**Comment by nathaliekhn** [comment]
An sich könnt ihr die Idee so umsetzen, ihr braucht aber keine Anmeldung (username, password). Bei euch fehlt allerdings die Anwendungslogik, so wie ich oben erwähnt habe.

**Comment by aselim21** [comment]
Bezüglich die Anwendungslogik: Das System wird Nutzer in einem Gesprächsraum einordnen abhängig von Sprache, Niveau, Lokation, Interessen usw. 

**Frage:** Können wir als Anwendungslogik noch dazu Sicherheit bieten? D.h. Das System wird das Benehmen verfolgen und anhand eine Methode wird es entscheiden, ob dieser Benutzer das System für das Böse benutzt und mißbraucht. 
* Ob er Gespräche innerhalb von 1 Minute verlässt(synchron oder asynchron??), oder 
* beleidigende Wörter für seine Namen benutzt(synchron), oder 
* im Chat jemanden beleidigt (asynchron).  

_Ist es richtig und was ist machbar?_

**Comment by nathaliekhn** [comment]
Wie genau hattet ihr euch denn die Zuordnung der Nutzer in einen Gesprächsraum vorgestellt? Wäre es sinnvoll einen Nutzer direkt IN den Raum einzuordnen oder diesen lieber selber die Entscheidung zu lassen, ob er das möchte oder nicht?

Ich habe mir nochmal Gedanken über euer Projekt gemacht. Ihr müsst einen externen Webservice für eine Übersetzung verwenden. Was genau leistet dann euer System? Nur eine Zuordnung dann ist etwas dünn. Macht euch doch noch ein paar Gedanken, welche Probleme ihr im Bereich "Sprache" finden könnt. Außerhalb eines Austauschs innerhalb eines Chats gibt es doch bestimmt noch mehr Möglichkeiten eine neue Sprache zu lernen. Bspw. eine visuelle Darstellung.

Bei dem Punkt Sicherheit verstehe ich nicht ganz, wie ihr den ersten Punkt (Ob er Gespräche innerhalb von 1 Minute verlässt) asynchron umsetzen wollt.
Generell könnt ihr Sicherheit mit einbauen, jedoch wird es sehr schwierig sein, diese umzusetzen. Dafür benötigt ihr sehr wahrscheinlich ein bestimmtes package.

**Comment by aselim21** [comment]
Unser Anwendungslogik ist ferig. Wir haben viele Änderungen gemacht. Alles steht bei Wiki :-) Wollten gerne wissen, ob wir es richtig gemacht haben. Danke

**Comment by nathaliekhn** [comment]
Ich werde leider aus der Dokumentation eurer Anwendungslogik nicht schlau. Was ist eine "Mission" und was ein "Panic Button"? Könntet ihr eure Anwendungslogik bitte textuell ausformulieren?

Zusätzlich ist mir aufgefallen, dass ihr auch schon Datenstrukturen gemacht habt. Das was ihr getan habt, ist jedoch nicht richtig. Mit Datenstrukturen sind die Daten gemeint, die ihr bei euren Ressourcen sendet oder zurück bekommt (bspw. eine JSON Datei). Die Datenstrukturen sollen zeigen, wie eure Ressourcen (wie z. B. der User) aufgebaut sind.

**Comment by bkumas** [comment]
Guten Abend,

wir haben unsere Anwendungslogik textuell ausformuliert und die Datenstruktur finden Sie als JSON Datei im Code.
Wir würden uns über Ihr Feedback freuen und wünschen Ihnen noch einen angenehmen Abend.

**Comment by nathaliekhn** [comment]
Von der Formulierung her, würde ich sagen, dass eure Anwendungslogik okay ist. Damit diese aber nicht zu dünn wird, solltet ihr darauf achten, dass ihr die Berechnungen, die für die Auswertung des Text-Dokuments benötigt wird, selbst durchführt bzw. programmiert.

Kurze Info: ihr sollt keine graphische Oberfläche machen. Diese ist nicht Teil der Bewertung. Ihr sollt euch nur auf das Backend konzentrieren.

Zu den Datenstrukturen: leider sehe ich keine Veränderung zu den vorherigen Inhalten, außer dass ihr die Überschrift durch "JSON-Datei" ergänzt habt. Schaut euch mal im Internet eine JSON an, dann wisst ihr was gemeint ist. Beispielsweise [hier](https://docs.microsoft.com/de-de/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver15) wird solch eine Datenstruktur aufgeführt.

**Comment by aselim21** [comment]
Vielen Dank für die Antwort. Wir freuen uns, das es in Ordnung ist. Passt das wenn wir in diesem Fall die filter Funktion von jQuery benutzen , aber die Bewertung natürlich selbst programmieren?

Die Graphische Oberfläche haben wir extra für uns gemacht, damit es auch für uns besser verständlich wird.

Ja, ist gemeint, dass die Json Dateie in Repository sind, also der Code ist nicht in Wiki. Wir sind auch nicht sicher, ob es viele Dateien geben soll, oder nur 1 Json Datei. 

Vielen Dank!

**Comment by nathaliekhn** [comment]
Mit der Filter-Funktion von jQuery bin ich nicht vertraut. Was macht diese denn und wofür würdet ihr die benutzen?

Und die Datenstrukturen bitte nicht in den Code reintun, sondern ins Wiki. Dort hat man auch die Möglichkeit Codeteile einzubinden. Und ihr benötigt schon einige JSON Dateien, damit ihr euer System testen könnt. Außerdem: warum habt ihr eine JSON-Datei für interest? Wie in dem anderen Issue gesagt: diese gehören zum User und sollten auch dort erwähnt werden.
