### ISSUE TITLE
Ressourcendefinition

### ISSUE THREAD

**Issue by aselim21** [bkumas/GDW-WS20-21#2]
Hallo, 

wir haben 2 Verionen von unserer Ressourcendefinition. Welcher ist auf dem richtigen Weg, weil beide komplett unterschiedlich sind? 
Version1:
[https://github.com/bkumas/GDW-WS20-21/blob/main/photos/issues/ressourcendefinition-version1.png](url) 
Version2:
[https://github.com/bkumas/GDW-WS20-21/blob/main/photos/issues/ressourcendefinition-version2.png](url)

**Comment by nathaliekhn** [comment]
Habe dieses Issue per Zufall gesehen. Denkt dran mich zu assignen, ansonsten könnten Issues untergehen.
Eure angegebenen Links führen leider zu keiner Datei. Vllt packt ihr das mal in euer Wiki.

**Comment by aselim21** [comment]
@nathaliekhn steht jetzt im Wiki

**Comment by nathaliekhn** [comment]
An sich wäre 2. Variante richtig. Nur wird es nicht so in der Tabelle dargestellt. Und auch nicht jede Ressource besitzt eine Sub oder Listenressource. Für die Tabelle benötigt ihr die URI; die HTTP-Methode, die auf der URI bzw. Ressource ausgeführt wird; die Semantik (was genau passiert mir der Ressource) und den content-type für den Response und den Request. Statuscodes sollten ebenfalls ausgeführt werden. Mehr Infos, wie was dargestellt wird, findet ihr im Buch "REST in Practice" von Jim Webber.

**Comment by bkumas** [comment]
@nathaliekhn Wir haben die Ressourcendefinition geändert und würden uns auf ein Verbesserungsvorschlag freuen. Dazu wollten wir noch Fragen in welchem Format die Ressourcen textuell definiert werden sollten.

**Comment by nathaliekhn** [comment]
Für mich sieht die 2. Tabelle richtig aus, welche unter Variante 3 steht. Bitte löscht noch Variante 1 und 2. Zusätzlich verstehe ich die oberste Tabelle nicht. Ihr benötigt lediglich die Tabelle, welche darunter steht. Also die Tabelle, in der die Statuscodes mit aufgeführt werden. Query-Parameter setzt ihr dort bitte zusammen in die URI ein, also bspw: _\user\{user_id}?interest=football_. Außerdem wird hinter interest nicht football geschrieben, sondern value. Value dient als Platzhalter für alle möglichen Interessen.
Zusätzlich ist _\interest_ keine Primärressource, sondern eine Subressource von User. Damit ihr auf die Interessen eines Users zugreifen könnt, benötigt ihr den jeweiligen Nutzer (also inklusive UserId) und dann seine Interessen. Das solltet ihr für eure Ressourcentabelle nochmal für alle Ressourcen überdenken und ggfs. anpassen.
