### ISSUE TITLE
Präsentation

### ISSUE THREAD

**Issue by aselim21** [bkumas/GDW-WS20-21#3]
Hallo,

Morgen ist ja die Präsentation und wir haben 15 minuten dafür. 
Werden wir vor den anderen Gruppen vorstellen?
Müssen wir alles was in Wiki steht präsentieren, also fachlich wie wir es gemacht haben, was unsere idee ist und die Tabellen erklären, oder wir müssen eher über unsere Arbeit in der Gruppe erzählen, wer was gemacht hat, welche Schwierigkeiten hatten wir usw.?

Danke im Voraus!

**Comment by nathaliekhn** [comment]
Hallo,

Ihr werdet nur vor Prof. Fischer und mir vortragen.
Wie ihr vortragt, ist euch überlassen.
Ihr solltet aber auf jeden Fall einen Einblick in die projektidee geben
